#SPDX-License-Identifier: MIT-0
---
# defaults file for security-updates
# roles/security-updates/defaults/main.yml

security_updates_autoclean_interval: 7
security_updates_unattended_upgrade: 1
security_updates_update_package_lists: 1
security_updates_download_upgradeable_packages: 1

