- import_playbook: set_host.yml

- hosts: adguard
  roles:
    - role: apt_proxy
      tags: [apt, proxy]

    - role: security
      tags: [security]
    - role: security-updates
      tags: [security]

    - role: docker
      tags: [docker]
    - role: adguard
      tags: [adguard]

    - role: promtail
      tags: [promtail, logging]

    - role: goss
      tags: [goss, tests]
