- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts: apt-cacher
  roles:
    - apt_proxy
    - ufw

    - security
    - security-updates

    - apt_cacher

    - promtail
    - goss
