- import_playbook: set_host.yml

- hosts: apt-cacher
  roles:
    - role: apt_proxy
      tags: [apt, apt_proxy]

    - role: security
      tags: [security]
    - role: security-updates
      tags: [security]

    - role: apt_cacher
      tags: [apt, apt-cacher]

    - role: promtail
      tags: [promtail]
    - role: goss
      tags: [goss, tests]
