- hosts: dev
  roles:
    - role: apt_proxy
      tags: [apt, apt_proxy]

    - role: docker
      tags: docker
    - role: security
      tags: security
    - role: security-updates
      tags: security
    - role: tailscale
      tags: tailscale

    - role dev
      tags: dev

    - role: promtail
      tags: promtail
