- hosts: frigate
  roles:
    - role: apt_proxy
      tags: [apt, apt_proxy]

    - role: security
      tags: security
    - role: security-updates
      tags: security

    - role: docker
      tags: docker
    - role: frigate
      tags: frigate

    - role: promtail
      tags: promtail
