- import_playbook: set_host.yml

- hosts: grafana
  roles:
    - role: apt_proxy
      tags: [apt, apt_proxy]

    - role: security
      tags: [security]
    - role: security-updates
      tags: [security]

    - role: docker
      tags: [docker]
    - role: grafana
      tags: [grafana]

    - role: promtail
      tags: [promtail]
    - role: goss
      tags: [tests, goss]
