- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts: grafana
  roles:
    - role: apt_proxy
      tags: proxy

    - role: security
      tags: security
    - role: security-updates
      tags: security

    - role: docker
    - role: grafana
      tags: grafana

    - role: promtail
      tags: promtail
    - role: goss
      tags: [goss, tests]
