- import_playbook: set_host.yml

- hosts: loki
  roles:
    - role: apt_proxy
      tags: [apt, apt_proxy]

    - role: security
      tags: [security]
    - role: security-updates
      tags: [security]

    - role: docker
      tags: [docker]
    - role: loki
      tags: [loki]

    - role: promtail
      tags: [promtail]
    - role: goss
      tags: [tests, goss]

