- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts: loki
  roles:
    - apt_proxy

    - security
    - security-updates

    - docker
    - loki

    - promtail
    #- goss

