- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts: prometheus
  roles:
    - apt_proxy

    - security
    - security-updates

    - docker
    - prometheus_pve_exporter
    - prometheus

    - promtail
    - goss
