- import_playbook: set_host.yml

- hosts: prometheus
  roles:
    - role: apt_proxy
      tags: [apt, apt_proxy]

    - role: security
      tags: [security]
    - role: security-updates
      tags: [security]

    - role: docker
      tags: [docker]
    - role: prometheus_pve_exporter
      tags: [prometheus]
    - role: prometheus
      tags: [prometheus]

    - role: promtail
      tags: [promtail]
    - role: goss
      tags: [tests, goss]
