- import_playbook: set_host.yml

- hosts:
  - traefik-0
  - traefik-1
  serial: 1
  roles:
    - apt_proxy

    - security
    - security-updates
    #- tailscale

    - docker
    - traefik

    - promtail
