- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts:
  - traefik-0
  roles:
    - apt_proxy

    - security
    - security-updates
    #- tailscale

    - docker
    - traefik

    - promtail
