- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts: vaultwarden
  roles:
    - apt_proxy

    - security
    - security-updates

    - docker
    - vaultwarden

    - promtail
    - rclone
