- import_playbook: set_host.yml
- import_playbook: disable_ipv6.yml

- hosts: whoogle
  roles:
    - apt_proxy

    - security
    - security-updates

    - docker
    - whoogle

    - promtail
    - goss
