plugin: community.general.proxmox
url: "https://192.168.0.14:8006"
user: "root@pam"
password: "{{ lookup('env', 'TF_VAR_proxmox_password') }}"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: false
keyed_groups:
  - key: proxmox_tags_parsed
    prefix: tag

