file:
    /etc/apt-cacher-ng/acng.conf:
        exists: true
        mode: "0644"
        owner: root
        group: root
        filetype: file
        contents: []
    /var/cache/apt-cacher-ng:
        exists: true
        mode: "2755"
        owner: apt-cacher-ng
        group: apt-cacher-ng
        filetype: directory
        contents: []
    /var/log/apt-cacher-ng/apt-cacher.log:
        exists: true
        mode: "0644"
        owner: apt-cacher-ng
        group: apt-cacher-ng
        filetype: file
        contents: []
port:
    tcp:3142:
        listening: true
        ip:
            - 0.0.0.0
    tcp6:22:
        listening: true
        ip:
            - '::'
    tcp6:3142:
        listening: true
        ip:
            - '::'
    tcp6:9080:
        listening: true
        ip:
            - '::'
package:
    ufw:
        installed: true
        versions:
            - 0.36.2-1
service:
    ufw:
        enabled: true
        running: true
    apt-cacher-ng.service:
        enabled: true
        running: true
    apt-daily-upgrade.service:
        enabled: true
        running: false
    apt-daily.service:
        enabled: true
        running: false
    postfix.service:
        enabled: true
        running: true
    postfix@.service:
        enabled: true
        running: false
    procps.service:
        enabled: true
        running: true
    promtail.service:
        enabled: true
        running: true
    proxmox-regenerate-snakeoil.service:
        enabled: true
        running: false
    unattended-upgrades.service:
        enabled: true
        running: true
command:
    ip -6 addr show dev eth0 | grep -q inet6:
        exit-status: 1
        stdout: ""
        stderr: ""
        timeout: 10000
    ufw status:
        exit-status: 0
        stdout:
            - 'Status: active'
        stderr: ""
        timeout: 10000
