port:
    tcp6:9080:
        listening: true
        ip:
            - '::'
service:
    docker:
        enabled: true
        running: true
group:
    docker:
        exists: true
        gid: 996
command:
    docker ps |grep -q grafana:latest:
        exit-status: 0
        stdout: ""
        stderr: ""
        timeout: 10000
    ip -6 addr show dev eth0 | grep -q inet6:
        exit-status: 1
        stdout: ""
        stderr: ""
        timeout: 10000

