
package:
    promtail:
        installed: true
        versions:
            - 3.6.3
port:
    tcp:3000:
        listening: true
        ip:
            - 0.0.0.0
    tcp6:9080:
        listening: true
        ip:
            - '::'
service:
    docker:
        enabled: true
        running: true
    promtail:
        enabled: true
        running: true
user:
    promtail:
        exists: true
        uid: 103
        gid: 65534
        groups:
            - docker
            - nogroup
            - systemd-journal
        home: /nonexistent
        shell: /bin/false
group:
    docker:
        exists: true
        gid: 996
command:
    docker inspect grafana|grep -i status:
        exit-status: 0
        stdout:
            - '"Status": "running",'
        stderr: ""
        timeout: 10000
    docker ps |grep -q grafana:latest:
        exit-status: 0
        stdout: ""
        stderr: ""
        timeout: 10000
    ip -6 addr show dev eth0 | grep -q inet6:
        exit-status: 1
        stdout: ""
        stderr: ""
        timeout: 10000
process:
    promtail:
        running: true
http:
    http://localhost:3000/api/health:
        status: 200
        allow-insecure: false
        no-follow-redirects: false
        timeout: 5000
        body:
            - '"database": "ok"'
