file:
    /etc/apt/detect-http-proxy:
        exists: true
        contents:
            - 192.168.0.39:3142
package:
    cron:
        installed: true
        versions:
            - 3.0pl1-162
    promtail:
        installed: true
        versions:
            - 3.6.3
    unattended-upgrades:
        installed: true
        versions:
            - 2.9.1+nmu3
port:
    tcp6:9080:
        listening: true
        ip:
            - '::'
service:
    cron:
        enabled: true
        running: true
    docker:
        enabled: true
        running: true
    promtail:
        enabled: true
        running: true
    unattended-upgrades:
        enabled: true
        running: true
user:
    promtail:
        exists: true
        uid: 103
        gid: 65534
        groups:
            - docker
            - nogroup
            - systemd-journal
        home: /nonexistent
        shell: /bin/false
group:
    docker:
        exists: true
        gid: 996
process:
    cron:
        running: true
    promtail:
        running: true
command:
  docker-loki-status:
    exit-status: 0
    stdout:
      - running
    exec: >
      docker inspect --format='{{"{{"}}.State.Status{{"}}"}}' loki

